# 服务器
server:
  port: 8081

web:
  domain: http://120.77.175.17


# spring
spring:
  # 数据连接池
  datasource:
    username: qdl
    password: qdl123
    url: jdbc:mysql://120.77.175.17/gallery?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource

  # 上传服务
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 上传路径
upload:
  dir : /home/qdl/Desktop/gallery/origin/
  newDir : /home/qdl/Desktop/gallery/new/

# 图片网络访问路径
img:
  imgURL: http://120.77.175.17:8081/origin/
  newImgURL: http://120.77.175.17:8081/new/